#!/bin/bash
host=$1
user=$2
password=$3
dat=webdata_now_p
val=W

# option check
if [ $# -lt 1 ]
then
  echo "Usage: $0 <host> [-t]"
  exit 1
fi
if [ $# -gt 1 ]
then
  dat=webdata_today_e
  val=kWh
fi
ping -c3 $host > /dev/null 2>&1
if [ $? -eq 0 ]
then
  p=$(curl -s  "$host"/status.html | grep "$dat = " | awk -F '"' '{print $2}')
  if [ "$p" = "" ]
  then
    sleep 1
    p=$(curl -s  "$host"/status.html | grep "$dat = " | awk -F '"' '{print $2}')
  fi
  if [ "$p" = "" ]
  then
    sleep 1
    p=$(curl -s  "$host"/status.html | grep "$dat = " | awk -F '"' '{print $2}')
  fi
  if [ "$p" = "" ]
  then
    sleep 1
    p=$(curl -s  "$host"/status.html | grep "$dat = " | awk -F '"' '{print $2}')
  fi
  if [ "$p" != "" ]
  then
    echo "$p $val"
    exit 0
  fi
  echo "Error: could not read data"
  exit 1
else
  echo "Error: connection to $host failed"
  exit 1
fi
