#!/bin/bash
#
# mi600
# MIT License Copyright (c) 2022 dr-ni
# https://github.com/dr-ni/mi600
#
# A simple bash command-line tool for direct solar data requests
# to the inverter Bosswerk mi600.
# It can read the actual solar power and the cumulative daily earned energy.
#
# Requirements: curl must be installed.
#
#
host=$1
auth=$2:$3
dat=webdata_now_p
val=''

# option check
if [ $# -lt 3 ]
then
  echo "Usage: $0 <host> <username> <password> [<type>] [-u]"
  echo "Valid types can be found in man page: 'man mi600'"
  echo "Option '-u': show unit"
  exit 1
fi
if [ $# -gt 3 ]
then
  if [ "$4" == "-u" ]
  then
    dat=webdata_now_p
    val=W
  else
    dat=$4
    val=''
    if [ "$5" == "-u" ]
    then
      [ "$dat" = "webdata_today_e" ] && val=kWh
      [ "$dat" = "webdata_total_e" ] && val=kWh
      [ "$dat" = "webdata_now_p" ] && val=W
    fi
  fi
fi
for i in 1 2 3
do
  p=$((curl -s -u "$auth" "$host"/status.html | grep "$dat = " | awk -F '"' '{print $2}' | sed 's/[[:space:]]*$//'))
  if [ "$p" != "" ]
  then
    echo "$p $val"
    exit 0
  fi
  sleep 3
done
ping -c3 $host > /dev/null 2>&1
if [ $? -eq 0 ]
then
  echo "mi600: could not read value"
else
  echo "Error: connection to $host failed"
fi
exit 1
